# -*- coding: utf-8 -*-
"""Aula13dez2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jq6y6-8MN8aiLyBynMZCU6RhPUeShAX5
"""

idade = 20
print(idade)
print(type(idade))

print()


# -1
bebida = "Café"
valor = 8.00
tipoBebida = "não alcoólica"
print("Minha bebida favorita é " + bebida + ", o tipo da bebida é " + tipoBebida + ", seu valor é de R$", valor)
print("bebida o tipo é ", type(bebida))
print("valor o tipo é ", type(valor))
print("tipobebida o tipo é ", type(tipoBebida))

print()

# 2-

bebida = "Café"
valor = 8.00
tipoBebida = "Não alcoólica"
print("Minha bebida favorita é {} o tipo da bebida é {}, seu valor é de R${}".format(bebida, tipoBebida, valor))



almoco_favorito = " Strogonoff"
preco = 59.9
orcamento = 100
troco = orcamento - preco

print()

print(troco)
print(orcamento + preco)
print("O preço do prato{} é R${}, o seu troco do valor R${} é de R${}".format(almoco_favorito,preco, orcamento, troco))

# estrutura condicionais almoço favorito

almoco_favorito = " Lasanha"
preco = 80.00
dinheiro = 60
cartao = 30
orcamento = dinheiro + cartao
troco= orcamento-preco

if (orcamento >= preco):
  if (dinheiro>=preco):
    print("Parabens você ira matar sua fome e pagara no dinheiro o valor de R${}" .format(dinheiro))
  else:
    restante_cartao = preco-dinheiro
    print("Parabens você pagou a{} com R${} em dinheiro e R${} no cartao, o total de RS{} seu troco foi de R${}" .format(almoco_favorito, dinheiro,restante_cartao,orcamento,troco) )
else:
  print("Mudança de planos. O almoço não vai ser esse hoje!!")

