# -*- coding: utf-8 -*-
"""Aula18dez2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vnNHBQny8Q4r2fGvYwWkQAA4fP3Qc_N7
"""

for i in range(6):
  print("robo, por favor regue a planta número " + str(i))

#Replicar usando o While

i = 0
while(i<6):
  print("robo, por favor regue a planta número " + str(i))
  i=i+1

#Replicar usando o While usanso o INCREMENTO +=1

i = 0
while(i<6):
  print("robo, por favor regue a planta número " + str(i))
  i+=1

for i in range(0, 6, 2):
    print("robo, por favor regue a planta número " + str(i))

i = 0
while i < 6:
    print("robo, por favor regue a planta número " + str(i))
    i += 2

