# -*- coding: utf-8 -*-
"""Bebidafavorita.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jq6y6-8MN8aiLyBynMZCU6RhPUeShAX5
"""

idade = 20
print(idade)
print(type(idade))

print()


# -1
bebida = "Café"
valor = 8.00
tipoBebida = "não alcoólica"
print("Minha bebida favorita é " + bebida + ", o tipo da bebida é " + tipoBebida + ", seu valor é de R$" + str(valor))
print("bebida o tipo é ", type(bebida))
print("valor o tipo é ", type(valor))
print("tipobebida o tipo é ", type(tipoBebida))

print()
# 2-

bebida = "Café"
valor = 8.00
tipoBebida = "Não alcoólica"
print("Minha bebida favorita é {} o tipo da bebida é {}, seu valor é de R${}".format(bebida, tipoBebida, valor))

